# Generated by Django 3.1.3 on 2020-11-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_exercise', models.TextField(default='', null=True)),
                ('image_exercise', models.ImageField(default='', null=True, upload_to='test_image')),
                ('language', models.CharField(default='', max_length=50, null=True)),
                ('exercise_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astigmatism_information', models.TextField()),
                ('color_blindness_information', models.TextField()),
                ('macular_degeneration_information', models.TextField()),
                ('dry_eye_information', models.TextField()),
                ('language', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='test_image')),
                ('option_one', models.CharField(max_length=20)),
                ('option_two', models.CharField(max_length=20)),
                ('option_three', models.CharField(max_length=20, null=True)),
                ('option_four', models.CharField(max_length=20, null=True)),
                ('answer', models.CharField(default='', max_length=20, null=True)),
                ('size', models.IntegerField(default=0, null=True)),
                ('test', models.CharField(max_length=50)),
                ('language', models.CharField(default='', max_length=50, null=True)),
                ('question_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astigmatism_test_result', models.CharField(default='', max_length=100)),
                ('color_blindness_test_result', models.IntegerField(default=0)),
                ('visual_acuity_test_result', models.IntegerField(default=0)),
                ('macular_degeneration_test_result', models.CharField(default='', max_length=100)),
                ('dry_eye_test_result', models.IntegerField(default=0)),
                ('accommodation_test_result', models.IntegerField(default=0)),
            ],
        ),
    ]
