# Generated by Django 3.1.3 on 2020-11-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer_pl',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='answer_ru',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_four_pl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_four_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_one_pl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_one_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_three_pl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_three_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_two_pl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_two_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question_ru',
            field=models.TextField(default='', null=True),
        ),
    ]
