# Generated by Django 3.1.3 on 2020-11-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0002_auto_20201119_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='language_pl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='language_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='text_exercise_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='text_exercise_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='astigmatism_information_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='astigmatism_information_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='color_blindness_information_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='color_blindness_information_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='dry_eye_information_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='dry_eye_information_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='macular_degeneration_information_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='macular_degeneration_information_ru',
            field=models.TextField(null=True),
        ),
    ]
