# Generated by Django 3.1.3 on 2020-11-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0003_auto_20201119_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_pl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_four',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_four_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_four_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_one',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_one_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_one_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_three',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_three_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_three_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_two',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_two_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_two_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
