# Generated by Django 3.1.3 on 2020-11-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0004_auto_20201119_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='image_exercise',
            field=models.ImageField(blank=True, default='', upload_to='test_image'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='language_pl',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='language_ru',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='text_exercise',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='text_exercise_pl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='text_exercise_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_pl',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_ru',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='test_image'),
        ),
        migrations.AlterField(
            model_name='test',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_four',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_four_pl',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_four_ru',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_three',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_three_pl',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='option_three_ru',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_pl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
