# Generated by Django 3.1.3 on 2020-11-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0005_auto_20201119_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='size',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
