# Generated by Django 3.1.3 on 2020-11-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0006_auto_20201126_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='size',
        ),
        migrations.AddField(
            model_name='test',
            name='size1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='size2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
