# Generated by Django 3.1.3 on 2020-11-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0007_auto_20201126_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='size1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='size2',
        ),
        migrations.AddField(
            model_name='test',
            name='size',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
