# Generated by Django 3.1.3 on 2020-12-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0008_auto_20201129_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='astigmatism_symptoms',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='information',
            name='astigmatism_treatment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='information',
            name='color_blindness_symptoms',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='information',
            name='color_blindness_treatment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='information',
            name='dry_eye_symptoms',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='information',
            name='dry_eye_treatment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='information',
            name='macular_degeneration_symptoms',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='information',
            name='macular_degeneration_treatment',
            field=models.TextField(default=''),
        ),
    ]
