# Generated by Django 3.1.3 on 2020-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0009_auto_20201201_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='astigmatism_symptoms_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='astigmatism_symptoms_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='astigmatism_treatment_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='astigmatism_treatment_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='color_blindness_symptoms_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='color_blindness_symptoms_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='color_blindness_treatment_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='color_blindness_treatment_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='dry_eye_symptoms_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='dry_eye_symptoms_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='dry_eye_treatment_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='dry_eye_treatment_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='macular_degeneration_symptoms_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='macular_degeneration_symptoms_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='macular_degeneration_treatment_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='macular_degeneration_treatment_ru',
            field=models.TextField(default='', null=True),
        ),
    ]
