# Generated by Django 3.1.3 on 2020-12-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0011_information1'),
    ]

    operations = [
        migrations.AddField(
            model_name='information1',
            name='disease_information_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information1',
            name='disease_information_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information1',
            name='disease_pl',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='information1',
            name='disease_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='information1',
            name='disease_symptoms_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information1',
            name='disease_symptoms_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information1',
            name='disease_treatment_pl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='information1',
            name='disease_treatment_ru',
            field=models.TextField(default='', null=True),
        ),
    ]
