# Generated by Django 3.1.3 on 2020-12-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaBadaniaWadWzroku', '0016_auto_20201220_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='language',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='language_pl',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='language_ru',
        ),
        migrations.RemoveField(
            model_name='information1',
            name='language',
        ),
        migrations.RemoveField(
            model_name='test',
            name='language',
        ),
        migrations.AddField(
            model_name='exercises',
            name='image_exercise_pl',
            field=models.ImageField(blank=True, default='', null=True, upload_to='test_image'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='image_exercise_ru',
            field=models.ImageField(blank=True, default='', null=True, upload_to='test_image'),
        ),
    ]
